### ISSUE TITLE
Circular dependency between TRY/MGL-PAX/NAMED-READTABLES

### ISSUE THREAD

**Issue by lukego** [melisgl/try#2]
I'm not sure if this qualifies as a bug but downstream I'm having trouble packaging up the latest Quicklisp distribution for the Nix package manager because of the circular dependency between TRY and NAMED-READTABLES (via MGL-PAX.) I think this is a new issue because it has been possible to package these systems together in the past.

I will look for a solution downstream but wanted to raise this & would welcome any practical advice.

The error is not occurring at the Lisp level but rather at the Nix level when trying to construct a DAG of dependencies between Quicklisp packages (including their test suites.) A workaround might be to suppress the test suite of NAMED-READTABLES to break the dependency back onto TRY (but I'm not sure yet.)

**Comment by melisgl** [comment]
TRY is indeed a new dependency of NAMED-READTABLES/TEST. TRY depends on MGL-PAX, which in turn depends on NAMED-READTABLES. The "including their test suites" bit is causing the trouble here, since on the ASDF system level the dependency graph is a DAG. So the obvious thing would be to package the test system separately (if at all).

**Comment by lukego** [comment]
Thanks for the tip! I'll exclude the test suite for now & think about whether this could all be better represented in Nix somehow.

I guess this dependency pattern is common in Lisp because there seem to be analogous situations with other combinations of packages and their test suites. I have never been a sophisticated user of ASDF myself :grin:

**Comment by Hellseher** [comment]
Hi,

The same issue presents in Guix downstream with this circular dependency flow: `try -> mgl-pax -> try`. This prevent to activate tests on both of them.

Thanks.

**Comment by melisgl** [comment]
@Hellseher Would the above suggestion of excluding the tests from the named-readtables package or packaging them separately work?

**Comment by melisgl** [comment]
I marked this as invalid, meaning working-as-intended, really.

**Comment by lukego** [comment]
Sounds good.

Managing the full ASDF model is a work on progress in those downstream packages :)
