### ISSUE TITLE
Is it possible to run the tests and get just the trial outcome even with unexpected events?

### ISSUE THREAD

**Issue by sabracrolleton** [melisgl/try#3]
This is a question rather than an issue (or maybe an enhancement request).

I know :print 'unexpected can limit what is printed to the results of the failing assertions. Is there a way to get only the summary object with no printing of failing assertions? It would help in regression testing. Thanks.

**Comment by melisgl** [comment]
Yes, with `:print nil`. Here, `nil` denotes a Lisp type. All events matching that type will be printed, which is none because it's the empty type.

**Comment by sabracrolleton** [comment]
Thank you. I have updated my report on testing-frameworks (https://sabracrolleton.github.io/testing-framework) to include Try. Please feel free to raise a PR at https://github.com/sabracrolleton/sabracrolleton.github.io with any corrections, additions or other comments.
