### ISSUE TITLE
Test failed on macOS on SBCL-2.3.7

### ISSUE THREAD

**Issue by catap** [melisgl/try#4]
The log:
```
:info:test Unhandled TRY-TEST::COND-A in thread #<SB-THREAD:THREAD "main thread" RUNNING
:info:test                                         {10013A0073}>:
:info:test   Condition TRY-TEST::COND-A was signalled.
:info:test Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10013A0073}>
:info:test 0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<TRY-TEST::COND-A {100349DF63}> #<unused argument> :QUIT T)
:info:test 1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<TRY-TEST::COND-A {100349DF63}>)
:info:test 2: (INVOKE-DEBUGGER #<TRY-TEST::COND-A {100349DF63}>)
:info:test 3: ((FLET "DEFTEST" :IN TRY-TEST::TEST-INVOKES-DEBUGGER) #<unused argument>)
:info:test 4: (TRY::CALL-TEST)
:info:test 5: (TRY-TEST::TEST-INVOKES-DEBUGGER)
:info:test 6: ((FLET "DEFTEST" :IN TRY-TEST::TEST-CHECKS) #<unused argument>)
:info:test 7: (TRY::CALL-TEST)
:info:test 8: (TRY-TEST::TEST-CHECKS)
:info:test 9: ((FLET "DEFTEST" :IN TRY-TEST::TEST-ALL) #<unused argument>)
:info:test 10: (TRY::CALL-TEST)
:info:test 11: (TRY-TEST::TEST-ALL)
:info:test 12: (TRY:TRY TRY-TEST::TEST-ALL :DEBUG NIL :COUNT NIL :COLLECT NIL :RERUN NIL :PRINT TRY:UNEXPECTED :DESCRIBE TRY:UNEXPECTED :STREAM NIL :PRINTER NIL)
:info:test 13: (TRY-TEST::TEST :DEBUG NIL :PRINT TRY:UNEXPECTED :DESCRIBE TRY:UNEXPECTED)
:info:test 14: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:TEST-OP > #<ASDF/SYSTEM:SYSTEM "try/test">)
:info:test 15: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
:info:test 16: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:TEST-OP > #<ASDF/SYSTEM:SYSTEM "try/test">) [fast-method]
:info:test 17: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1001C0FEF3}>) [fast-method]
:info:test 18: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
:info:test 19: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1001C0FEF3}>) [fast-method]
:info:test 20: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:TEST-OP > #<ASDF/SYSTEM:SYSTEM "try"> :PLAN-CLASS NIL :PLAN-OPT
IONS NIL) [fast-method]
:info:test 21: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:TEST-OP > #<ASDF/SYSTEM:SYSTEM "try">)
:info:test 22: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
:info:test 23: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:TEST-OP > #<ASDF/SYSTEM:SYSTEM "try">) [fast-method]
:info:test 24: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:TEST-OP COMMON-LISP-USER::TRY)
:info:test 25: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
:info:test 26: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:TEST-OP COMMON-LISP-USER::TRY) [fast-method]
:info:test 27: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10042A3D2B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
:info:test 28: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
:info:test 29: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002C2DC5B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
:info:test 30: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:TEST-OP COMMON-LISP-USER::TRY) [fast-method]
:info:test 31: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:OPERATE (QUOTE ASDF/LISP-ACTION:TEST-OP) (QUOTE COMMON-LISP-USER::TRY)) #<NULL-LEXENV>)
:info:test 32: (EVAL (ASDF/OPERATE:OPERATE (QUOTE ASDF/LISP-ACTION:TEST-OP) (QUOTE COMMON-LISP-USER::TRY)))
```

**Comment by melisgl** [comment]
What hardware platform and macOS versions is this?
Also, is this SBCL at the tag sbcl-2.3.7 or the latest HEAD?

**Comment by catap** [comment]
macOS 12; SBCL is installed from MacPorts which is tag sbcl-2.3.7

**Comment by melisgl** [comment]
I couldn't reproduce this. What I tried was:
- compile a fresh checkout SBCL 2.3.7 on arm64 macOS v12.6 (mac mini 2020, Apple M1)
- install quicklisp
- clone latest try from github
- add it to quicklisp/local-projects/
- `(ql:quickload "try")`
- `(asdf:test-system "try")`
- observed that all tests pass.

The check that fails seems to be this:

```
(is (null (invokes-debugger (cond-a :handler t)
              (invoke-debugger (make-condition 'cond-a))
              47)))
```

Do you perhaps have an `SB-EXT:*INVOKE-DEBUGGER-HOOK*` that interferes with the test? How do you run the test?

**Comment by melisgl** [comment]
Also, what does `locale` say in the shell and what is the value of `CUSTOM:*DEFAULT-FILE-ENCODING*` in CLISP?

**Comment by catap** [comment]
@melisgl I'm a maintaner of almost all lisp ports in MacPorts and easy way to reproduce the issue is run it via MacPorts by `port test cl-try test.run=yes` (right now tests are disabled).

At the end it simple runs `(asdf:operate (quote asdf:test-op) (quote ${name}))` where `${name}` is all `.asd` files without `.asd` :) Yes, in the loop.

In couple of hours I'll able to make for you an easy reproducer via Github CI.

**Comment by melisgl** [comment]
No need. I can reproduce this with `sbcl --disable-debugger`, which does install a debugger hook.

**Comment by melisgl** [comment]
What's happening is this: `--disable-debugger` replaces the debugger with a function that exits the lisp. Try's `invokes-debugger` macro binds `cl:*debugger-hook*` to a function that records whether the debugger is entered and calls the shadowed value of `cl:*debugger-hook*`. Not calling it would be screw up code compositionality even worse than calling it.

I think there is no right fix to this within Try because `--disable-debugger` is an explicit request that must be honored, and it makes the test impossible to run. A better fix would be to have SBCL's `--non-interactive` switch arrange for exiting the lisp if it would block on reading input, which is often the intention, of which `--disable-debugger` handles only one special case.

- **Hack 1**: Add a timeout around running the tests, which is pretty much unavoidable anyway, and don't use `--disable-debugger`.

- **Hack 2**: Make `try-test::test` (the entry point to the tests) call `sb-debug:enable-debugger`. The downside, of course, is that normal lisp errors will now block.

- **Hack 3**: Autoskip `invokes-debugger` checks when the debugger is disabled. Not running tests is bad though.

- **Hack 4**: Instead of `--disable-debugger`, handle blocking on stdin more generally by taking input from `/dev/null` and making `*debug-io*` use stdin/stdout (normally it accesses the terminal).

    ```
    sbcl --eval '(setq *debug-io* (make-two-way-stream *standard-input* *standard-output*))'  \
         --eval '(asdf:test-system "try")' --eval '(sb-ext:exit :code 42)' < /dev/null
    ```

I think Hack 4 is the clear winner. What do you think?

**Comment by melisgl** [comment]
@catap, would the above Hack 4 be a feasible workaround for you?

**Comment by catap** [comment]
@melisgl well... the issue that I'm using that way to test for a while and right now I've created ports for more than 200 packets... This is the first port that I'm encountered with this issue to be honest and I not sure that using pipe's via tcl's system (which is used inside MacPorts where I'm making my ports) is good idea and won't lead to another issue :)

**Comment by melisgl** [comment]
@catap, Yes. I expect no other package has this kind of  debugger behaviour test.
I assume you prefer Hack 3, then?

**Comment by catap** [comment]
@melisgl right now I disable tests on that port. Maybe it is the best option and technically seems like 3rd way but outside of your codebase.

**Comment by melisgl** [comment]
Yeah, that may be the best.
