### ISSUE TITLE
Cyclic dependencies with mgl-pax

### ISSUE THREAD

**Issue by catap** [melisgl/try#5]
I'm packaging the lisp software into MacPorts and discovered a kind of cyclic dependency which I can't solve.

Right now `try` depends on `mgl-pax` by docs. And `mgl-pax` depends on `try` by some tests.

An easy way to avoid that seems to introduce `try-docs` system which will depend on `mgl-pax` and `try`.

Or make something like `mgl-pax-base` like `metatilities-base`.

Is it possible?

**Comment by melisgl** [comment]
This is very similar to https://github.com/melisgl/try/issues/2. Please read my explanation there. The gist of it is that the dependency graph is only cyclic when all asdf systems within pax and try are collapsed into a single graph node each. On the level of individual asdf system level, there are no cyclic dependencies.

**Comment by catap** [comment]
@melisgl how can I keep separated documentation or test systems when it is ships as single `.asd` file?

**Comment by melisgl** [comment]
Even though there are multiple asdf systems defined in the same file, there could be one package (terminology: port?) built per asdf system. Would that be too granular? Alternative, exclude the tests from the package.

**Comment by catap** [comment]
@melisgl here a two cycles.
 - `try` -> `mgl-pax` -> `try` via `mgl-pax/test` and `mgl-pax/test-extension`;
 - `trivial-utf-8` -> `mgl-pax` -> `trivial-utf-8` via `trivial-utf-8/doc` and `mgl-pax/document`.

The only way to "exclude" it that I see right now is edit `.asd` file on packaging.

I not sure that it is good idea because it means that at some point it may explode again as soon as someone would like to depends on `mgl-pax/test` for example.

Yeah, I saw at least `clack`/`lack` which depends on its test-systems :(

**Comment by melisgl** [comment]
There is also the named-readtables cycle in the linked issue. Your description of the problem indicates that some script takes an `.asd` file as the input and creates a package that includes all systems defined in it. I'm suggesting changing the script so that it can be told what to include or exclude. Am I misunderstanding the situation?

Some of these cycles are there to allow dependencies of PAX to use PAX for their documentation, or to be able to use Try to test PAX and PAX to document Try. It's kind of a bootstrapping situation that poses a problem for package builders that map all asdf systems in a single file to a single package.

**Comment by catap** [comment]
"some script" is simple call `(asdf:operate (quote asdf:${op}) (quote ${name}))` where `${op}` is `build-op` or `test-op`, and `${name}` is a name of asd-file without `.asd` which fails on missed dependencies.

The issue that MacPorts (and I assume many other packaging system) expects that dependency hasn't got cycle.

And I can't figure it out how to make packages which can be both build and test via such call without introducing dependency cycle.

If I exclude `try` from dependencies of `mgl-pax`, it can be built but can't be test. Also, when it is installed, it has missed dependencies on installed test system which can be re-used by other packages.

**Comment by melisgl** [comment]
There is a cycle between asdf _files_, but there is no cycle between the asdf _systems_. This distinction is crucial. The `asdf:operate` line operates on a single asdf system. Presumably, what asdf systems are defined in the same `.asd` file comes into play somewhere, but your example does not demonstrate where.

I'm still suggesting that you exclude the asdf system `mgl-pax/test` from the `mgl-pax` package. I expected this would be an easy workaround and I can't yet see why it isn't.

**Comment by catap** [comment]
> I'm still suggesting that you exclude the asdf system `mgl-pax/test` from the `mgl-pax` package. I expected this would be an easy workaround and I can't yet see why it isn't.

By patching asd-file?

**Comment by catap** [comment]
Thus, I need also to exclude `mgl-pax/document` because it is the second cycle with `trivial-utf-8`.

**Comment by melisgl** [comment]
Editing asdf files makes future conflicts very likely and should be a last resort, but maybe that's easier in your build system than adding include/exclude parameters to the build.

Do not exclude `mgl-pax/document` as that renders pax unable to generate documentation.

What I'm saying is that a possible workaround is to
- exclude `trivial-utf-8/doc` from the `trivial-utf-8` package;
- exclude `mgl-pax/test` from the `mgl-pax` package;
- exclude `named-readtables/doc` from the `named-readtables` package.

Another workaround is to put everything in trivial-utf-8, try, named-readtables, and pax into package `pax-and-deps` and make `mgl-pax`, `try`, etc be dummy packages that depend `pax-and-deps`.

Ideally, the build system should be able to map all valid asdf dependency graphs without manual intervention.

**Comment by catap** [comment]
@melisgl how can I exclude `mgl-pax/test` without editing `.asd`?

**Comment by catap** [comment]
@melisgl how can I exclude `mgl-pax/test` without editing `.asd`?

The build system works like this:
 - unpack archive to `source/<name>/...`;
 - create symlings for `.asd` into `system/`;
 - run `(asdf:operate (quote asdf:build-op) (quote ${name}))` where `${name}` is name of each new `.asd` file without `.asd`.
 
 Before it runs, it install dependencies for that package. And here I do have cycles.
 
 I may switch off "run" part which allows me to install everything, but I can't be sure that I haven't missed some dependencies.
 
 So, I don't understand how can I exclude some system without editing files which I really not like to do.

**Comment by melisgl** [comment]
I think something must be missing from that description because only building the `mgl-pax` asdf system will not build `mgl-pax/navigate`, `mgl-pax/document`, etc, which are autoloaded.

Also, how are the dependencies determined and what is "install" (is it quicklisp, untar, something else)?

**Comment by catap** [comment]
@melisgl "build" phase for `mgl-pax` works as expected. The issue that autoloaded parts won't work without installing dependencies => I must add `trivial-utf-8` to dependencies otherwise it installs "broken" package.

If I add `trivial-utf-8` to dependency I have a loop because it depends on `mgl-pax`.

The same with `try` because it installs `/test` system which depends on `try` and which depends on `mgl-pax`.

BTW install is simple unpack an archive like untar.

**Comment by melisgl** [comment]
OK, so dependencies are packages on the MacPorts level. Right?

You didn't answer how package dependencies are determined. I guess you take the union of all asdf system dependencies somehow mapping them back to macport packages?

You also didn't say anything about this option:
> Another workaround is to put everything in trivial-utf-8, try, named-readtables, and pax into package pax-and-deps and make mgl-pax, try, etc be dummy packages that depend pax-and-deps.

**Comment by catap** [comment]
> OK, so dependencies are packages on the MacPorts level. Right?

Yes, you're correct.

> You didn't answer how package dependencies are determined. I guess you take the union of all asdf system dependencies somehow mapping them back to macport packages?

Yes, it is union on all installed `.asd` files. Some packages like `ppcre` are easy to split into parts because it ships two `.asd` files and I simple create a port for each file.

> You also didn't say anything about this option:
> 
> > Another workaround is to put everything in trivial-utf-8, try, named-readtables, and pax into package pax-and-deps and make mgl-pax, try, etc be dummy packages that depend pax-and-deps.

Sorry, I have missed it.

Well... I don't like this idea to be honest. It requires to fetch 3 independent sources from two different platforms and mix everything up.

**Comment by melisgl** [comment]
> Yes, it is union on all installed `.asd` files. Some packages like `ppcre` are easy to split into parts because it ships two `.asd` files and I simple create a port for each file.

If you could treat a single `.asd` file as two files (putting e.g. `mgl-pax/test` in the imaginary second file), then you could implement the first workaround.

> > You also didn't say anything about this option:
> > > Another workaround is to put everything in trivial-utf-8, try, named-readtables, and pax into package pax-and-deps and make mgl-pax, try, etc be dummy packages that depend pax-and-deps.
> 
> Sorry, I have missed it.
> 
> Well... I don't like this idea to be honest. It requires to fetch 3 independent sources from two different platforms and mix everything up.

Well, so far I suggested three options:
- exclude some systems from certain packages, or
- split some libraries into xxx, xxx-doc, xxx-test packages as necessary, and then there are no cyclic dependencies, or
- put some libraries into the same packages and add dummy packages for the individual ones.

I'd be happy solve this in the affected libraries, but the dependencies are there for a reason, and it all works in ASDF and Quicklisp. Unfortunately, with these dependencies, the natural heuristic of mapping all asdf systems in the same `.asd` file to the same package doesn't to work.

If I understand correctly (and please confirm this), maintaining the packages would be easier if the `mgl-pax/test` asdf system were renamed to `mgl-pax-test` and moved to `mgl-pax-test.asd`? (Plus similar moves, e.g. `trivial-utf-8/doc` -> `trivial-utf-8-doc`). That is, all systems in the same asdf file could be put into the same package without creating cyclic dependencies.

The downsides to this solution are that
- the name of some systems must change,
- what the name is would depend on the presence of dependencies in the universe,
- it solves a packaging problem at the wrong level,
- it is not easily testable (i.e. ASDF has a more flexible take on dependencies, so one could easily break the promise of no-asdf-file-dependency-cycles).

On the other hand, multiple package systems must solve the same issue, so committing the required information to the affected libraries in some form makes sense.  So @catap, @lukego, @Hellseher, would the one-asd-file-per-package (MacPort/Nix/Guix) approach work for you all, or do you prefer another way?

**Comment by catap** [comment]
> If I understand correctly (and please confirm this), maintaining the packages would be easier if the `mgl-pax/test` asdf system were renamed to `mgl-pax-test` and moved to `mgl-pax-test.asd`? (Plus similar moves, e.g. `trivial-utf-8/doc` -> `trivial-utf-8-doc`). That is, all systems in the same asdf file could be put into the same package without creating cyclic dependencies.

Yes, this is the simplest to support solution by package manager.

It turns into mapping one-to-one between `.asd` and packages, that allows to make packages like `mgl-pax-test` and `mgl-pax-doc` easy.

**Comment by melisgl** [comment]
@catap `dref/dref.asd` and `mgl-pax.asd` also have cyclic dependencies. These files are in the same repository (this one). You didn't mention this cycle because it is somehow not a problem for macports or for some other reason (e.g. because there was an earlier failure)?

**Comment by catap** [comment]
@melisgl I haven't mention it to keep discussion as simple as I can.

Anyway, I've tried to extract `dref` as dedicated package and encounter another loop. For time being I've just "mix" bot packages into one port, but if we may split it.. well, it makes things cleaner.

And thanks to keep working on it. If I may assist you in any way feel free to ask.

**Comment by melisgl** [comment]
Changes:
- `mgl-pax/bootstrap` was renamed to `mgl-pax-bootstrap` (and now lives in `mgl-pax-bootstrap.asd`, of course)
- `mgl-pax/test` was renamed to `mgl-pax-test` (now in `mgl-pax-test.asd`)
- `named-readtables/doc` was removed
- `named-readtables` now depends on `mgl-pax-bootstrap`
- `trivial-utf-8/doc` was removed
- `trivial-utf-8` now depends on `mgl-pax-bootstrap`

https://github.com/melisgl/mgl-pax/commit/48f3b5a37abea2c2e3cd6abbb4a39a077ad6f3f4
https://gitlab.common-lisp.net/trivial-utf-8/trivial-utf-8/-/commit/41421c98507bfa7dc5623aa997c4245e44dfcd4d
https://github.com/melisgl/named-readtables/commit/7a60d455c1ac8a3fc25890307f421a87133482ff

I *think* this makes the `.asd` file dependency graph acyclic. Please test.

**Comment by catap** [comment]
@melisgl are you sure that `mgl-pax-bootstrap` should depends on `mgl-pax/test` for `test-op`?

**Comment by melisgl** [comment]
No, it's not needed at all. It was a why-not decision. Shall I remove it?

**Comment by catap** [comment]
> No, it's not needed at all. It was a why-not decision. Shall I remove it?

Yes, if it possible.

**Comment by melisgl** [comment]
Done.

**Comment by catap** [comment]
`named-readtables` depends on `mgl-pax-bootstrap` but for test it requires `try` which depends on `mgl-pax` which depends on `named-readtables`.

Seems the only one cycle is left which can be broken by extracting `named-readtables/test` into dedicated `.asd`.

Thus, extracting `dref/test*` into dedicated `.asd` allows to make dedicated package for `dref` :)

**Comment by catap** [comment]
Well, `dref/test*` depends on `try` which depends on `mgl-pax` whcih depends on `dref`...

=> moving `dref/test*` into dedicated `.asd` seems like something nessesary.

**Comment by melisgl** [comment]
Hopefully, these will do:
https://github.com/melisgl/mgl-pax/commit/3c3509a947eddbbd84d48eae998a59da4617cc4b
https://github.com/melisgl/named-readtables/commit/81586cebc5236d6648460ea23fcc3f1d052bd050

**Comment by catap** [comment]
Minor remarks:

1. `named-readtables-test.asd` seems to be broken by 
```
:info:build   of #P"/opt/local/var/macports/build/_Users_catap_src_macports-ports_lisp_cl-named-readtables/cl-named-readtables-test/work/build/source/cl-named-readtables-test/named-readtables-test.asd":
:info:build Unhandled LOAD-SYSTEM-DEFINITION-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1004780113}>: Error while trying to load definition for system named-readtables-test from pathname /opt/local/var/macports/build/_Users
_catap_src_macports-ports_lisp_cl-named-readtables/cl-named-readtables-test/work/build/source/cl-named-readtables-test/named-readtables-test.asd: don't recognize component type :FILE
:info:build Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1004780113}>
...
:info:build Command failed: /opt/local/bin/sbcl --no-sysinit --no-userinit --non-interactive --eval '(require :asdf)' --eval '(setf asdf:*central-registry* (list* (quote *default-pathname-defaults*) #p"/opt/local/var/macports/build/_Users_catap_src_macports-ports_lisp_cl-named-readtables/cl-named-readtables-test/work/build/system/" #p"/opt/local/share/common-lisp/system/" asdf:*central-registry*))' --eval '(asdf:operate (quote asdf:build-op) (quote named-readtables-test))' 2>&1
```

2. Some system has `test:op` dependency to test's system. For example `dref.asd`. I not sure that it will broke anything on my side, need more time to play and to test.

**Comment by catap** [comment]
The next found things. `dref/test` system was renamed into `dref-test` but it uses by old name at dependency at `mgl-pax-test.asd`

**Comment by melisgl** [comment]
Sorry about those issues. Fixed in:
https://github.com/melisgl/mgl-pax/commit/7a07993b2a96a7679e1638f8bb0342bdf0ce42d7
https://github.com/melisgl/named-readtables/commit/40f979602bba168109534121bb24cb6daf980f76

As to `test:op` dependencies on the test system, those should stay as they make `(asdf:test-system ...)` work. Those shouldn't be hard dependencies, at most something like 'Suggests' in Debian.

**Comment by catap** [comment]
> Sorry about those issues. Fixed in: [melisgl/mgl-pax@7a07993](https://github.com/melisgl/mgl-pax/commit/7a07993b2a96a7679e1638f8bb0342bdf0ce42d7) [melisgl/named-readtables@40f9796](https://github.com/melisgl/named-readtables/commit/40f979602bba168109534121bb24cb6daf980f76)

np, just start one more testing, will be back as soon as it's done.


> As to `test:op` dependencies on the test system, those should stay as they make `(asdf:test-system ...)` work. Those shouldn't be hard dependencies, at most something like 'Suggests' in Debian.

Unfortunately here no such things as recommended dependency on MacPorts :(

**Comment by catap** [comment]
After some thought I guess if someone installs `dref` and tries to run tests from CLI and it fails on missed systems `dref-test`... well, it seems fair enough to have that dependency missed to avoid the cycle but keep here `dref-test` which also need to be installed for that wired case.

And if anyone would like to use anywhere `dref-test` system he probably add dependency to the port / package `dref-test` and not `dref`.

Just to confirm. I've split everything into a few ports:
- cl-dref
- cl-dref-test
- cl-mgl-pax-bootstrap
- cl-mgl-pax
- cl-mgl-pax-test
- cl-named-readtables
- cl-named-readtables-test
- cl-trivial-utf-8
- cl-try

And all was suceffuly build and tested by: `SBCL 2.3.7`, `CCL 1.12.2`, `ABCL 1.9.2`, `ECL 21.2.1` and `CLisp 2.49.93+` on macOS 12.

**Comment by melisgl** [comment]
Thank you for confirming that it works. Hopefully, the packaging efforts of @lukego and @Hellseher benefit from these changes as well.
